const $=id=>document.getElementById(id);
let state={points:0,total:0,taps:0,party:-1,partyTaps:0,receipt:''};
try{const saved=JSON.parse(localStorage.getItem('bananace-v1'));if(saved&&['points','total','taps','partyTaps'].every(k=>Number.isSafeInteger(saved[k])&&saved[k]>=0)&&Number.isInteger(saved.party)&&saved.party>=-1&&saved.party<parties.length&&saved.total>=saved.points)state={...state,...saved,receipt:typeof saved.receipt==='string'?saved.receipt:''}}catch{}
let tab='tap',voted=false,method='RUB',selectedBank=0,series=0,timer,pressAnimation,flashAnimation;
const fmt=n=>n.toLocaleString('ru-RU');const rub=n=>(n*11/1000000).toLocaleString('ru-RU',{minimumFractionDigits:6,maximumFractionDigits:6});
const levelIndex=()=>levels.reduce((n,l,i)=>state.taps>=l.at?i:n,0);
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
function save(){try{localStorage.setItem('bananace-v1',JSON.stringify(state))}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('visible'),2600)}
function bananaUrl(l){return 'assets/bananas/banana-'+String(l.sheet*25+l.cell).padStart(3,'0')+'.png'}
function spriteStyle(l){return 'background-image:url("'+bananaUrl(l)+'")'}
function setSprite(el,l){el.style.backgroundImage='url("'+bananaUrl(l)+'")';el.style.backgroundPosition='center';el.setAttribute('aria-label',l.name)}
function render(){const idx=levelIndex(),l=levels[idx],next=levels[idx+1];$('points').textContent=fmt(state.points);$('header-taps').textContent=fmt(state.taps)+' ТАПОВ / ОЧКИ';$('money').textContent=rub(state.points)+' ₽';$('balance').textContent=rub(state.points)+' ₽';$('tap-count').textContent='НАЖАТИЙ: '+fmt(state.taps);$('level-label').textContent='№ '+String(idx+1).padStart(3,'0')+' / 100';$('rarity-label').textContent=seriesNames[l.sheet];$('level-name').textContent=l.name;$('level-desc').textContent=l.desc;setSprite($('banana-img'),l);$('progress-text').textContent=next?fmt(state.taps)+' / '+fmt(next.at)+' ТАПОВ':'100 / 100';$('progress-fill').style.width=(next?(state.taps-l.at)/(next.at-l.at)*100:100)+'%';$('next-level').textContent=next?'Дальше: '+next.name:'Абсолют. Выше только потолок.';$('evolutions').textContent=idx;const p=parties[state.party];$('effect-name').textContent=p?p.name:'Сам по себе';$('effect-desc').textContent=p?p.good+'. '+p.bad+'.':'Один тап — одно очко.';$('per-tap').textContent=p?p.good.toUpperCase():'+1 ЗА ТАП';$('receipt').textContent=state.receipt||'Транзакций пока нет.';$('withdraw-button').disabled=state.points===0;$('bank-panel').hidden=method!=='RUB';$('conversion').textContent=method==='RUB'?'На вывод: '+rub(state.points)+' ₽':'На вывод: '+rub(state.points)+' BAN · курс 1:1';}
function insideCircle(x,y,rect){const radius=Math.min(rect.width,rect.height)/2;return (x-rect.left-rect.width/2)**2+(y-rect.top-rect.height/2)**2<=radius**2}
function calculateGain(p,n,points){let gain=p?p.gain:1;if(p?.skip&&n%p.skip===0)gain=0;if(p?.bonus&&n%p.bonus===0)gain=p.bonusGain;if(p?.loss&&n%p.loss===0)gain=-p.lossValue;if(p?.tax&&n%p.tax===0)gain=p.taxGain;return Math.max(-points,gain)}
function tap(event){const rect=$('banana').getBoundingClientRect();if(event&&!insideCircle(event.clientX,event.clientY,rect))return false;if(state.total>Number.MAX_SAFE_INTEGER-100)return false;const prev=levelIndex();state.taps++;state.partyTaps++;const gain=calculateGain(parties[state.party],state.partyTaps,state.points);state.points+=gain;state.total+=Math.max(0,gain);save();render();$('per-tap').textContent=(gain>=0?'+':'')+gain+' / ПОПАДАНИЕ';if(!reduceMotion.matches){pressAnimation?.cancel();flashAnimation?.cancel();pressAnimation=$('banana-img').animate([{transform:'scale(1)'},{transform:'scale(.95) rotate(-2deg)',offset:.35},{transform:'scale(1)'}],{duration:180,easing:'ease-out'});flashAnimation=document.querySelector('.hit-flash').animate([{opacity:.8,transform:'scale(.82)'},{opacity:0,transform:'scale(1)'}],{duration:230,easing:'ease-out'})}if(levelIndex()>prev){toast('ОТКРЫТ: '+levels[levelIndex()].name);if(!reduceMotion.matches)$('level-name').animate([{color:'#f8e328'},{color:'#ffffff'}],{duration:600})}return gain;}
function showTab(name){if(!['tap','collection','withdraw','party','ads','miner','cases'].includes(name))throw new Error('Неизвестная вкладка');if(tab!==name&&name==='party')voted=false;tab=name;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===name));document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-current',b.dataset.tab===name?'page':'false')});document.body.dataset.page=name;if(name==='collection')renderCollection();if(name==='party')renderParties();if(typeof renderArcade==='function')renderArcade();render();window.scrollTo({top:0,behavior:'instant'});}
function renderCollection(){const idx=levelIndex();$('levels').innerHTML=levels.slice(series*25,series*25+25).map((l,j)=>{const i=series*25+j;return `<button class="collectible ${i>idx?'locked':''} ${i===idx?'current':''}" data-banana="${i}" aria-label="Осмотреть: ${l.name}"><span class="tag">№ ${String(i+1).padStart(3,'0')} <span>${i>idx?'ЗАКРЫТ':i===idx?'ТВОЙ':'В КОЛЛЕКЦИИ'}</span></span><span class="banana-sprite" role="img" aria-label="${l.name}" style="${spriteStyle(l)}"></span><h3>${l.name}</h3><span class="threshold">${fmt(l.at)} тапов <i>↗</i></span></button>`}).join('');$('levels').querySelectorAll('[data-banana]').forEach(b=>b.onclick=()=>{const l=levels[Number(b.dataset.banana)];setSprite($('specimen-art'),l);$('specimen-name').textContent=l.name;$('specimen-desc').textContent=l.desc;$('specimen-series').textContent=seriesNames[l.sheet];$('specimen-threshold').textContent=fmt(l.at)+' ТАПОВ / '+(state.taps>=l.at?'ОТКРЫТ':'ЕЩЁ '+fmt(l.at-state.taps));$('specimen').showModal()});document.querySelectorAll('[data-series]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.series)===series))}
function renderParties(){$('parties').innerHTML=parties.map((p,i)=>`<article class="party-card ${state.party===i?'selected':''}"><img class="party-flag" src="assets/flags/party-${i}.svg" alt="Флаг партии ${p.name}" loading="lazy"><div class="party-top"><span class="party-emblem">${String(i+1).padStart(2,'0')}</span><span class="party-symbol">${['ЕР','НЛ','КП','ЛД','СК','СОН','Я','ЗЛ','ПИ','РЦ','КК','РД','ГП','ПП','ППШ','ЛН','ЧЕК','СУ','НВ','БМ'][i]}</span></div><h2>${p.name}</h2><p>${p.slogan}</p><div class="party-stats"><p class="buff">${p.good}</p><p class="debuff">${p.bad}</p></div><button data-vote="${i}" ${voted?'disabled':''}>${voted?(state.party===i?'ВЫБРАНО':'ДО СЛЕДУЮЩЕГО ВИЗИТА'):'МОЙ ВЫБОР ↗'}</button></article>`).join('');$('parties').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(voted)return;state.party=Number(b.dataset.vote);state.partyTaps=0;voted=true;save();render();renderParties();toast('Новый эффект: '+parties[state.party].name)})}
$('banana').addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();tap(e)});$('banana').addEventListener('click',e=>{if(e.detail===0)tap()});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showTab(b.dataset.go));document.querySelector('.brand').onclick=e=>{e.preventDefault();showTab('tap')};document.querySelectorAll('[data-series]').forEach(b=>b.onclick=()=>{series=Number(b.dataset.series);renderCollection()});$('close-specimen').onclick=()=>$('specimen').close();
document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{method=b.dataset.method;document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('selected',x===b));render()});
$('withdraw-button').onclick=()=>{if(!state.points)return;$('confirm-text').textContent=`Вывести ${rub(state.points)} ${method==='RUB'?'₽':'BAN'}? ${method==='RUB'?'Банк: '+banks[selectedBank].name+'. ':''}Баланс ${fmt(state.points)} очков будет обнулён. Коллекция сохранится.`;$('confirm').showModal()};$('confirm').addEventListener('close',()=>{if($('confirm').returnValue!=='confirm'||!state.points)return;state.receipt=`${new Date().toLocaleString('ru-RU')} · ${rub(state.points)} ${method==='RUB'?'₽ · '+banks[selectedBank].name:'BAN'} · демо-перевод завершён`;state.points=0;save();render();toast('Готово. Баланс обнулён, коллекция на месте.')});
$('ad-grid').innerHTML=ads.map((a,i)=>`<article class="ad"><div class="ad-art" role="img" aria-label="${a[0]}" style="background-position:${i%6*20}% ${Math.floor(i/6)*20}%"><span class="ad-label">${i===15?'НОВИНКА':i%3===0?'ХИТ ДВОРА':'РЕКЛАМА'}</span></div><div class="ad-copy"><small>BLACK MARKET / ${String(i+1).padStart(2,'0')}</small><h2>${a[0]}</h2><p>${a[1]}</p><button data-ad="${i}">${a[2]} ↗</button></div></article>`).join('');$('ad-grid').querySelectorAll('button').forEach(b=>b.onclick=()=>toast(['Отдел обещаний уже обрабатывает твоё разочарование.','Товар закончился в тот момент, когда ты поверил.','Заявка принята. Результат не предусмотрен.','Рекламодатель ушёл за хлебом. Навсегда.'][Number(b.dataset.ad)%4]));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_bananace_progress',description:'Read local game progress. All money is fictional.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');return{points:state.points,taps:state.taps,totalEarned:state.total,banana:levels[levelIndex()].name,level:levelIndex()+1,collectionSize:levels.length,partyCount:parties.length,adCount:ads.length,tab}}})).catch(()=>{})}catch{}}
render();
