const banks=[{name:'Сбёрбанк',mark:'СБ',color:'#69be70'},{name:'Тынькофф',mark:'Т',color:'#edda42'},{name:'Альфа-Банан',mark:'АБ',color:'#ef635b'},{name:'ВТБ — Вот Твой Банан',mark:'ВБ',color:'#6c9fea'},{name:'Газмясбанк',mark:'ГМ',color:'#6ac4d2'},{name:'Почти Банк',mark:'ПБ',color:'#b998e8'}];
const skinNames=['P250 | Песок в кармане','Glock-18 | Зелёная тоска','MP9 | Изолента','Nova | Дедова антресоль','UMP-45 | Ковёр из гаража','ПП-Бизон | Синяя ржавчина','AK-47 | Фанерный авторитет','M4A1-S | Клетчатый провал','Desert Eagle | Баллончик','AWP | Короткое замыкание','AK-47 | Кислотный отпуск','Керамбит | Золотая кожура'];
const skinWeights=[20,18,16,14,10,8,6,4,2,1.5,.45,.05];
const skins=skinNames.map((name,i)=>({id:i,name,weight:skinWeights[i],rarity:i<8?'ШИРПОТРЕБ':i===8?'НЕОБЫЧНЫЙ':i===9?'РЕДКИЙ':i===10?'ОЧЕНЬ РЕДКИЙ':'ЛЕГЕНДА',color:i<8?'#96a4b3':i===8?'#8f79df':i===9?'#d969dc':i===10?'#ec6c56':'#edc954',image:'assets/skins/skin-'+String(i).padStart(3,'0')+'.png'}));
const randomUnit=()=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296};
function pickSkin(r){if(!Number.isFinite(r)||r<0||r>=1)throw new Error('Random value outside [0,1)');let sum=0;for(let i=0;i<skins.length;i++){sum+=skins[i].weight;if(r*100<sum)return i}return skins.length-1}
function createMineBoard(random=randomUnit){return Array.from({length:20},()=>{const hp=1+Math.floor(random()*3);return{hp,max:hp,gold:random()<.35?3+Math.floor(random()*10):0}})}
function emptyArcade(){return{mine:{gold:0,depth:1,power:1,hits:0,board:createMineBoard()},cases:{counts:Array(12).fill(0),opened:0,last:null,pending:null}}}
function readArcade(raw){const fallback=emptyArcade();if(!raw)return fallback;try{const value=JSON.parse(raw),m=value.mine,c=value.cases;const uint=n=>Number.isSafeInteger(n)&&n>=0;if(!m||!c||!uint(m.gold)||!uint(m.depth)||m.depth<1||!uint(m.hits)||!Number.isInteger(m.power)||m.power<1||m.power>5||!Array.isArray(m.board)||m.board.length!==20||!m.board.every(t=>uint(t.hp)&&t.hp<=t.max&&t.max>=1&&t.max<=3&&uint(t.gold)&&t.gold<=12)||!Array.isArray(c.counts)||c.counts.length!==12||!c.counts.every(uint)||!uint(c.opened)||c.counts.reduce((a,b)=>a+b,0)!==c.opened||![c.last,c.pending].every(x=>x===null||Number.isInteger(x)&&x>=0&&x<12))return fallback;return value}catch{return fallback}}
let arcade;try{arcade=readArcade(localStorage.getItem('bananace-arcade-v1'))}catch{arcade=emptyArcade()}
let spinAnimation=null,spinTimer=null,spinning=false,spinEpoch=0;
function saveArcade(){try{localStorage.setItem('bananace-arcade-v1',JSON.stringify(arcade))}catch{}}
function bankRender(){$('bank-methods').innerHTML=banks.map((b,i)=>`<button class="bank-choice ${selectedBank===i?'selected':''}" data-bank="${i}" aria-pressed="${selectedBank===i}"><b style="--bank:${b.color}">${b.mark}</b><span>${b.name}</span></button>`).join('');$('bank-methods').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedBank=Number(b.dataset.bank);bankRender()})}
function mineCell(index){const m=arcade.mine,t=m.board[index];if(!t||t.hp===0)return false;t.hp=Math.max(0,t.hp-m.power);m.hits++;if(!t.hp){m.gold+=t.gold;$('mine-message').textContent=t.gold?`Жила! Максим нашёл ${t.gold} золота.`:'Пустая порода. Максим не унывает.'}else $('mine-message').textContent='Камень треснул. Ещё '+Math.ceil(t.hp/m.power)+' уд.';saveArcade();renderMine();return true}
function renderMine(){const m=arcade.mine,cleared=m.board.filter(t=>t.hp===0).length;$('mine-gold').textContent=fmt(m.gold);$('mine-depth').textContent=fmt(m.depth);$('mine-power').textContent=m.power+' / 5';$('mine-cleared').textContent=cleared+' / 20';$('mine-board').innerHTML=m.board.map((t,i)=>`<button class="rock ${t.hp===0?(t.gold?'gold-found':'dug'):t.hp<t.max?'cracked':''}" data-rock="${i}" ${t.hp===0?'disabled':''} aria-label="Клетка ${i+1}: ${t.hp===0?(t.gold?'найдено '+t.gold+' золота':'пусто'):'порода, осталось '+Math.ceil(t.hp/m.power)+' ударов'}"><span>${t.hp===0?(t.gold?'+'+t.gold:'·'):'×'+Math.ceil(t.hp/m.power)}</span><small>${t.hp===0?(t.gold?'ЗОЛОТО':'ПУСТО'):'ПОРОДА'}</small></button>`).join('');$('mine-board').querySelectorAll('button').forEach(b=>b.onclick=()=>mineCell(Number(b.dataset.rock)));const cost=m.power*25;$('mine-upgrade').textContent=m.power===5?'КИРКА МАКСИМУМ':'УЛУЧШИТЬ · '+cost+' ЗОЛОТА';$('mine-upgrade').disabled=m.power>=5||m.gold<cost;$('mine-next').disabled=cleared!==20;$('mine-next').textContent=cleared===20?'СПУСТИТЬСЯ НА СЛОЙ '+(m.depth+1):'РАСКОПАЙ СЛОЙ ДО КОНЦА'}
function upgradePick(){const m=arcade.mine,cost=m.power*25;if(m.power>=5||m.gold<cost)return false;m.gold-=cost;m.power++;saveArcade();renderMine();$('mine-message').textContent='Новая кирка. Сила удара: '+m.power;return true}
function nextMineLayer(){if(arcade.mine.board.some(t=>t.hp>0))return false;arcade.mine.depth++;arcade.mine.board=createMineBoard();saveArcade();renderMine();$('mine-message').textContent='Новый слой. Максим ещё глубже в работе.';return true}
function skinCard(s,extra=''){return `<div class="skin-card ${extra}" style="--rarity:${s.color}"><img src="${s.image}" alt="${s.name}" draggable="false"><small>${s.rarity}</small><strong>${s.name}</strong></div>`}
function renderCases(){const c=arcade.cases;$('case-count').textContent='ОТКРЫТО: '+fmt(c.opened);$('inventory-count').textContent=fmt(c.opened)+' скинов';$('case-spin').disabled=spinning;$('case-spin').textContent=spinning?'КРУТИМ…':'КРУТИТЬ БЕСПЛАТНО';if(!spinning){$('case-result').textContent=c.last===null?'Крути. Может, хоть сейчас повезёт.':'ВЫПАЛО: '+skins[c.last].name;$('case-result').style.color=c.last===null?'':skins[c.last].color}const owned=skins.filter(s=>c.counts[s.id]>0);$('case-inventory').innerHTML=owned.length?owned.map(s=>`<article class="inventory-item">${skinCard(s)}<span class="skin-quantity">×${fmt(c.counts[s.id])}</span></article>`).join(''):'<div class="empty-inventory">Пока пусто. Первый кейс уже ждёт.</div>';if(!$('case-reel').children.length)$('case-reel').innerHTML=skins.slice(0,8).map(s=>skinCard(s)).join('')}
function finishSpin(){if(arcade.cases.pending===null)return;const winner=arcade.cases.pending;arcade.cases.counts[winner]++;arcade.cases.opened++;arcade.cases.last=winner;arcade.cases.pending=null;spinning=false;saveArcade();renderCases();toast('Выпало: '+skins[winner].name)}
function spinCase(){if(spinning)return false;const epoch=++spinEpoch,winner=pickSkin(randomUnit());spinning=true;arcade.cases.pending=winner;saveArcade();const pool=Array.from({length:36},()=>skins[pickSkin(randomUnit())]);pool[29]=skins[winner];const reel=$('case-reel');reel.innerHTML=pool.map(s=>skinCard(s)).join('');reel.style.transform='translateX(0px)';renderCases();$('case-result').textContent='ПОДВАЛ РЕШАЕТ…';const target=reel.children[29],destination=$('case-window').clientWidth/2-(target.offsetLeft+target.offsetWidth/2);const duration=reduceMotion.matches?0:3400;clearTimeout(spinTimer);spinAnimation?.cancel();if(duration){spinAnimation=reel.animate([{transform:'translateX(0px)'},{transform:`translateX(${destination}px)`}],{duration,easing:'cubic-bezier(.12,.7,.1,1)',fill:'forwards'});spinTimer=setTimeout(()=>{if(epoch!==spinEpoch)return;reel.style.transform=`translateX(${destination}px)`;spinAnimation?.cancel();finishSpin()},duration)}else{reel.style.transform=`translateX(${destination}px)`;finishSpin()}return true}
function renderArcade(){if(tab==='miner')renderMine();if(tab==='cases')renderCases()}
function resetAllProgress(){spinEpoch++;clearTimeout(spinTimer);spinAnimation?.cancel();spinning=false;state={points:0,total:0,taps:0,party:-1,partyTaps:0,receipt:''};arcade=emptyArcade();voted=false;method='RUB';selectedBank=0;series=0;try{localStorage.removeItem('bananace-v1');localStorage.removeItem('bananace-arcade-v1')}catch{}$('case-reel').innerHTML='';$('case-reel').style.transform='none';document.querySelectorAll('[data-method]').forEach(b=>b.classList.toggle('selected',b.dataset.method==='RUB'));bankRender();renderMine();renderCases();showTab('tap');toast('Чистый лист. Первый банан снова твой.')}
$('mine-upgrade').onclick=upgradePick;$('mine-next').onclick=nextMineLayer;$('case-spin').onclick=spinCase;bankRender();
$('reset-button').onclick=()=>$('reset-dialog').showModal();$('reset-dialog').addEventListener('close',()=>{if($('reset-dialog').returnValue==='reset')resetAllProgress()});
$('case-odds').innerHTML=skins.map(s=>`<div><span>${s.name}</span><b>${s.weight.toLocaleString('ru-RU')}%</b></div>`).join('');
if(arcade.cases.pending!==null)finishSpin();
window.addEventListener('storage',e=>{if(e.key==='bananace-v1'&&e.newValue===null){spinEpoch++;clearTimeout(spinTimer);spinAnimation?.cancel();spinning=false;state={points:0,total:0,taps:0,party:-1,partyTaps:0,receipt:''};arcade=emptyArcade();voted=false;render();renderArcade()}else if(e.key==='bananace-arcade-v1'&&!spinning){arcade=readArcade(e.newValue);renderArcade()}});
